#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-magic
Version  : 0.4.12
Release  : 1
URL      : https://github.com/ahupp/python-magic/archive/0.4.12.tar.gz
Source0  : https://github.com/ahupp/python-magic/archive/0.4.12.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: python-magic-python
BuildRequires : file
BuildRequires : file-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
# python-magic
python-magic is a python interface to the libmagic file type
identification library.  libmagic identifies file types by checking
their headers according to a predefined list of file types. This
functionality is exposed to the command line by the Unix command
`file`.

%package python
Summary: python components for the python-magic package.
Group: Default

%description python
python components for the python-magic package.


%prep
%setup -q -n python-magic-0.4.12

%build
export LANG=C
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python2 setup.py test || :
%install
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
